### ISSUE TITLE
How to use WebUi as replacement for Microsoft Webview2 ?

### ISSUE THREAD

**Issue by commanderz** [webui-dev/pascal-webui#4]
You did not try to use webui as a replacement for webview in order to serve an interface that already exists as a separate website?
I have used Microsoft edge webview2 and compare the webui capabilities with it. 
So far it seems that something is missing, what do you say?

**Comment by AlbertShown** [comment]
Of course, you can switch to WebUI. Your app will become multi-platform, no GUI dependencies needed. The only challenge part is the webui Pascal wrapper is not up to date. Perhaps if you have free time, you can contribute to it to make it up to date.

**Comment by delphius** [comment]
> So far it seems that something is missing, what do you say?

The answer will depend on how you use webview2 to work with the site. If a library like [fpwebview](https://github.com/PierceNg/fpwebview) is used, it provides the same capabilities as webui, but is limited to one browser (edge) and one platform (windows). If we are talking about full-fledged interaction with the browser at the api level and components for Lazarus or Delphi forms, such as [WebView4Delphi](https://github.com/salvadordf/WebView4Delphi), then this will require a more complete reworking of the interaction mechanism, because webui is not embedded in the form for classic applications, but completely replaces them.

**Comment by hassandraga** [comment]
On top of what @delphius said, I want to clarify that `WebView` is an OS-specific library, and it is embedded in your application as a dependency. In addition, All WebViews in all OS do not provide all technologies like a real web browser. 

Conversely, WebUI is a module you can add to your application to use any web browser as GUI, which makes you access the full potential of web browsers (JS APIs, WebAssembly...).

**Comment by delphius** [comment]
> The only challenge part is the webui Pascal wrapper is not up to date

updated the wrapper version to library version 2.4.0

**Comment by delphius** [comment]
> So far it seems that something is missing, what do you say?

So what exactly did you have in mind, taking into account the above explanations?
